server:
  port: 8080

cloud:
   aws:
     s3:
       endpoint: https://s3.amazonaws.com
     credentials:
       access-key: AKIAQUM7QY6SGL7KBCSX
       secret-key: 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
     bucket: url-qogustj
   region:
     static: ap-northeast-2
   stack:
     auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://meetup.cqwxdf1sdeiw.ap-northeast-2.rds.amazonaws.com:3306/qogustj
    username: admin
    password: qogustj50

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB