server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://meetup.cqwxdf1sdeiw.ap-northeast-2.rds.amazonaws.com:3306/qogustj
    username: admin
    password: qogustj50

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 799333127259-2e22vu6n71ctc579itbpvpdivoa8am99.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email, profile